/* 女训 MVP：规则引擎始终可用；AI 和专业 Skill 通过服务端代理接入。 */
(() => {
  'use strict';
  const K={p:'nvx.userProfile',c:'nvx.dailyCheckins',w:'nvx.workoutLogs',e:'nvx.events',a:'nvx.aiConfig',d:'nvx.deviceId'};
  const $=s=>document.querySelector(s), app=$('#app'), toastEl=$('#toast');
  const today=()=>new Date().toISOString().slice(0,10), now=()=>new Date().toISOString();
  const read=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}};
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]));
  const date=v=>{const d=new Date(v+'T12:00:00');return `${d.getMonth()+1}月${d.getDate()}日`};
  let device=localStorage.getItem(K.d);if(!device){device=`local-${Math.random().toString(36).slice(2,8)}`;localStorage.setItem(K.d,device)}

  const profileFields=[
    ['ageRange','你的年龄段',['18—24 岁','25—34 岁','35—44 岁','45—54 岁','55 岁以上','不想回答']],
    ['bodyStage','你现在的身体阶段',['有规律月经','有月经，但不太规律','经前反应明显','正在经历或接近围绝经期','已经绝经','不确定 / 不想回答']],
    ['activityLevel','你目前的运动状态',['几乎不运动，但想开始','偶尔运动，难以坚持','每周运动 1—2 次','每周运动 3 次及以上','曾经规律运动，现在中断了','正在恢复训练']],
    ['goals','你想从训练中获得什么？',['建立运动习惯','变强壮 / 有力量','减脂塑形','改善疲劳和精力','改善经前/经期状态','增加肌肉，预防衰老','减少疼痛或不适'],true,'最多选择 3 项'],
    ['trainingPlace','你更常在哪里训练？',['居家无器械','居家小器械','健身房','户外','都可以']]
  ];
  const checkinFields=[
    ['sleep','昨晚睡眠',['好','一般','差']],['energy','今日精力',['高','中','低']],['pain','疼痛或不适',['无','轻微','明显']],['soreness','肌肉酸痛 / 关节不适',['无','轻微','明显']],['stressMood','情绪 / 压力',['稳定','有点压力','压力很大 / 情绪波动明显']],['cycleStatus','月经 / 经前状态',['非经期，状态稳定','经期第 1—2 天','经期第 3 天及以后','经前疲劳 / PMS 明显','周期不规律 / 不确定','不适用']],['trainingIntent','今天的训练意愿',['很想练','可以练','不太想练','只想轻轻动一下']]
  ];
  const workouts=[
    {id:'starter_strength_15',title:'15 分钟新手安全力量',duration:'15 分钟',intensity:'低',equipment:'无器械',desc:'适合想开始力量训练、又担心受伤的今天。',steps:['热身：原地踏步 2 分钟','椅子辅助深蹲 8 次 × 2 组','墙壁俯卧撑 8 次 × 2 组','臀桥 10 次 × 2 组','死虫式 8 次 × 2 组','拉伸放松 2 分钟'],safe:'动作过程中如果出现明显疼痛，请停止。'},
    {id:'whole_strength_20',title:'20 分钟全身力量',duration:'20 分钟',intensity:'中',equipment:'无器械',desc:'一次稳稳完成的居家力量练习，兼顾下肢、上肢与核心。',steps:['动态热身 3 分钟','深蹲 10 次 × 3 组','俯身划船动作模拟 10 次 × 3 组','俯卧撑或跪姿俯卧撑 8 次 × 2 组','臀桥 12 次 × 3 组','平板支撑 20 秒 × 2 组','放松 2 分钟'],safe:'保持动作可控；腰背有不适时减少幅度。'},
    {id:'advanced_strength_25',title:'25 分钟全身力量进阶',duration:'25 分钟',intensity:'中高',equipment:'无器械',desc:'适合状态不错时，把力量训练做得扎实一点。',steps:['热身 5 分钟','深蹲 12 次 × 3 组','反向弓步 8 次 × 3 组','俯卧撑 8 次 × 3 组','臀桥单腿变化 8 次 × 2 组','平板支撑 30 秒 × 3 组','放松 3 分钟'],safe:'动作质量优先。关节疼痛、头晕或异常不适时立即停止。'},
    {id:'low_impact_20',title:'20 分钟低冲击训练',duration:'20 分钟',intensity:'低',equipment:'无器械',desc:'保留训练节奏，同时对恢复更友好。',steps:['关节活动 3 分钟','低冲击开合步 45 秒 × 3 组','半程深蹲 10 次 × 2 组','站姿提膝 45 秒 × 2 组','鸟狗式 8 次 × 2 组','拉伸 4 分钟'],safe:'全程保持可以正常说话的强度；不舒服就放慢或改成散步。'},
    {id:'period_relief_10',title:'10 分钟经期舒缓',duration:'10 分钟',intensity:'很低',equipment:'无器械',desc:'轻柔活动身体，今天只需要照顾好自己。',steps:['腹式呼吸 2 分钟','猫牛式 1 分钟','婴儿式停留 1 分钟','仰卧抱膝 1 分钟','坐姿前屈 1 分钟','轻柔髋部活动 2 分钟','放松呼吸 2 分钟'],safe:'如果疼痛明显或流血量异常，建议休息，不强行训练。'},
    {id:'sleep_reset_8',title:'8 分钟睡前放松',duration:'8 分钟',intensity:'很低',equipment:'无器械',desc:'把训练目标换成放松和恢复，也是一种完成。',steps:['慢呼吸 2 分钟','颈肩放松 1 分钟','胸椎旋转 1 分钟','腿后侧拉伸 1 分钟','靠墙抬腿 2 分钟','安静呼吸 1 分钟'],safe:'动作只做到舒适范围，不需要追求拉伸幅度。'},
    {id:'walk_stretch_30',title:'30 分钟快走 + 拉伸',duration:'30 分钟',intensity:'低',equipment:'户外',desc:'不想正式训练时，用一段快走延续和身体的连接。',steps:['轻松走 5 分钟','快走 20 分钟','小腿、臀腿、肩颈拉伸 5 分钟'],safe:'以能说完整句子的速度走；天气或身体不适时改为室内轻活动。'},
    {id:'core_stability_15',title:'15 分钟核心稳定',duration:'15 分钟',intensity:'低中',equipment:'无器械',desc:'低冲击地练习稳定和控制，适合想保持节奏的今天。',steps:['热身 2 分钟','死虫式 8 次 × 2 组','鸟狗式 8 次 × 2 组','侧桥 15 秒 × 2 组','臀桥 12 次 × 2 组','拉伸 3 分钟'],safe:'腰部不适时缩短动作范围，始终保持顺畅呼吸。'}
  ];
  const copy={
    '冲刺日':{tone:'sprint',explain:'你的睡眠、精力和训练意愿都不错，身体目前适合承受更高质量的训练。今天可以安排力量训练、技术练习或稍高强度训练。',advice:'今天可以练得更认真一点，但不需要为了证明自己而硬冲。动作质量优先。',encourage:'状态好的时候，把训练做扎实，就是长期变强的底气。',ids:['advanced_strength_25','whole_strength_20','core_stability_15']},
    '常规日':{tone:'regular',explain:'你的整体状态稳定，适合完成一次正常训练。今天不用追求突破，保持节奏就是有效训练。',advice:'选择一套中等强度训练，完成后记录身体感觉。',encourage:'长期训练不是每天都冲，而是大多数日子都能稳稳出现。',ids:['whole_strength_20','core_stability_15','walk_stretch_30']},
    '降载日':{tone:'deload',explain:'你的身体状态提示今天不适合硬冲。可能是睡眠、经前疲劳、疼痛、酸痛或压力影响了恢复。今天可以降低重量、减少组数，保留训练节奏。',advice:'今天的目标不是突破，而是维持节奏、避免受伤。',encourage:'降低强度不是退步，是更聪明地长期变强。',ids:['starter_strength_15','low_impact_20','sleep_reset_8']},
    '恢复日':{tone:'recovery',explain:'你的身体正在发出需要恢复的信号。今天不建议做高强度训练，可以选择轻活动、拉伸、散步，或者认真休息。',advice:'如果有明显疼痛、异常不适或持续不适，请优先休息，必要时咨询医生。',encourage:'休息不是中断训练，而是训练计划的一部分。',ids:['period_relief_10','walk_stretch_30','sleep_reset_8']}
  };
  let S={mode:new URLSearchParams(location.search).get('mode')==='admin'?'admin':'user',screen:'welcome',profile:{...read(K.p,{})},checkin:{},feedback:{},workout:null,last:null,tab:'overview',ai:'我会结合你今天的打卡，帮你把“硬练还是放弃”变成一个可执行的选择。'};
  function calc(c){let score=5;const m={sleep:{'好':2,'一般':0,'差':-2},energy:{'高':2,'中':0,'低':-2},pain:{'无':1,'轻微':-1,'明显':-3},soreness:{'无':1,'轻微':-1,'明显':-3},stressMood:{'稳定':1,'有点压力':-1,'压力很大 / 情绪波动明显':-2},cycleStatus:{'非经期，状态稳定':1,'经期第 1—2 天':-2,'经期第 3 天及以后':-1,'经前疲劳 / PMS 明显':-2,'周期不规律 / 不确定':0,'不适用':0},trainingIntent:{'很想练':2,'可以练':1,'不太想练':-1,'只想轻轻动一下':-2}};Object.entries(m).forEach(([k,v])=>score+=v[c[k]]||0);let dayType=score>=9?'冲刺日':score>=6?'常规日':score>=3?'降载日':'恢复日';if(c.pain==='明显')dayType='恢复日';if(c.soreness==='明显'&&dayType==='冲刺日')dayType='降载日';if(c.sleep==='差'&&c.energy==='低'&&['冲刺日','常规日'].includes(dayType))dayType='降载日';if(c.cycleStatus==='经期第 1—2 天'&&c.pain!=='无')dayType='恢复日';if(c.cycleStatus==='经前疲劳 / PMS 明显'&&c.stressMood==='压力很大 / 情绪波动明显'&&['冲刺日','常规日'].includes(dayType))dayType='降载日';/* 验收/Demo：经前疲劳但仍愿意训练且没有明显疼痛时，保留降载选择。 */if(c.cycleStatus==='经前疲劳 / PMS 明显'&&c.pain!=='明显'&&c.trainingIntent!=='只想轻轻动一下'&&dayType==='恢复日')dayType='降载日';return{score,dayType,copy:copy[dayType],workouts:copy[dayType].ids.map(id=>workouts.find(w=>w.id===id))}}
  function eventLog(type,detail='',level='info'){const a=read(K.e,[]);a.unshift({at:now(),type,detail,level,device});save(K.e,a.slice(0,60))}
  function tip(t){toastEl.textContent=t;toastEl.classList.add('visible');clearTimeout(tip.t);tip.t=setTimeout(()=>toastEl.classList.remove('visible'),2600)}
  const header=(back='')=>`<header class="topbar"><div class="brand"><span class="brand-mark">力</span>女训</div>${back?`<button class="icon-button" data-a="${back}" aria-label="返回">←</button>`:'<button class="text-button" data-a="admin">运营台</button>'}</header>`;
  const nav=()=>`<nav class="bottom-nav"><button class="nav-item ${S.screen==='checkin'?'active':''}" data-a="nav" data-s="checkin"><b>◉</b>今日</button><button class="nav-item ${['result','workout','feedback'].includes(S.screen)?'active':''}" data-a="nav" data-s="result"><b>⌁</b>训练</button><button class="nav-item ${S.screen==='records'?'active':''}" data-a="nav" data-s="records"><b>▤</b>记录</button><button class="nav-item ${S.screen==='privacy'?'active':''}" data-a="nav" data-s="privacy"><b>□</b>隐私</button></nav>`;
  function shell(content,bottom=true){app.innerHTML=`<section class="shell">${content}${bottom?nav():''}</section>`}
  function field([key,label,opts,multi,hint],draft,kind){const chosen=multi?(draft[key]||[]):draft[key];return `<fieldset class="question"><legend>${label}${hint?`<span class="question-hint">${hint}</span>`:''}</legend><div class="choice-grid ${opts.length<=4?'two':''}">${opts.map(v=>{const on=multi?chosen.includes(v):chosen===v;return `<button type="button" class="choice ${multi?'check':''} ${on?'selected':''}" data-a="pick" data-kind="${kind}" data-k="${key}" data-v="${esc(v)}"><span class="dot"></span>${esc(v)}</button>`}).join('')}</div></fieldset>`}
  function latest(){const a=read(K.c,[]).sort((x,y)=>y.date.localeCompare(x.date));const c=a.find(x=>x.date===today())||a[0];return c?{...calc(c),score:c.score,dayType:c.dayType}:null}

  function welcome(){shell(`${header()}<section class="hero"><p class="eyebrow">TODAY, YOUR WAY</p><h1>长寿的女人，<em>任何时候</em>都可以开始训练。</h1><div class="hero-rule"></div><p>根据你的月经周期、睡眠、精力、疼痛和训练意愿，判断今天适合怎么练。</p><button class="button button-primary" data-a="start">开始今日训练判断</button><button class="button button-quiet" data-a="go" data-s="privacy">查看隐私说明</button></section><div class="privacy-strip"><strong>默认只在本机保存。</strong> 不登录、不上传、不接广告 SDK，不用于广告推荐。你随时可以清除数据。</div>`,false)}
  function profile(){shell(`${header('home')}<p class="eyebrow">FIRST, A LITTLE CONTEXT</p><h1 class="page-title">先认识一下<br>你的训练起点。</h1><p class="form-intro">这些信息只保存在当前浏览器，帮我们把建议做得更贴近你。</p><form id="profile-form">${profileFields.map(f=>field(f,S.profile,'profile')).join('')}<button class="button button-primary">保存并进入今日打卡</button></form>`)}
  function checkin(){if(!read(K.p,null)){S.screen='profile';return render()}shell(`${header()}<p class="eyebrow">1 MINUTE CHECK-IN · ${date(today())}</p><h1 class="page-title">今天的你，<br>状态如何？</h1><p class="form-intro">没有正确答案。按你此刻最真实的感觉选择。</p><form id="checkin-form">${checkinFields.map(f=>field(f,S.checkin,'checkin')).join('')}<button class="button button-primary">生成今日训练建议</button></form>`)}
  const card=w=>`<button class="workout-card" data-a="workout" data-id="${w.id}"><span class="tag">${w.duration}</span><span class="tag coral">${w.intensity}强度</span><h3>${w.title} →</h3><p>${w.desc}</p></button>`;
  function result(){const r=S.last||latest();if(!r){S.screen='checkin';return render()}const c=r.copy; shell(`${header()}<p class="eyebrow">YOUR TRAINING DECISION</p><section class="result-hero ${c.tone==='recovery'?'recovery':c.tone==='deload'?'deload':''}"><span class="result-score">状态评分 ${r.score} / 15+</span><h1>今天是${r.dayType}</h1><p>${c.explain}</p></section><p class="recommendation-copy"><strong>今天怎么练：</strong>${c.advice}</p><div class="section-head"><h2 class="section-title">选一个现在做得到的</h2><span class="tiny">2—3 个选择</span></div><div class="workout-list">${r.workouts.map(card).join('')}</div><div class="callout"><strong>给今天的你：</strong>${c.encourage}</div>${aiCard()}`)}
  function aiCard(){const configured=read(K.a,{}).aiEndpoint;return `<section class="ai-card"><div class="ai-head"><span class="ai-orb">✦</span><div><h3>问问女训助手</h3><p>${configured?'已连接通用 AI 服务':'演示模式：本地安全回复'} · 医疗问题请咨询医生</p></div></div><div class="ai-message" id="ai-message">${esc(S.ai)}</div><form id="ai-form" class="ai-form"><input name="message" maxlength="160" placeholder="例如：今天想练腿，怎么调整？" aria-label="向女训助手提问"><button class="button button-primary small">问问</button></form></section>`}
  function workout(){const w=workouts.find(x=>x.id===S.workout);if(!w){S.screen='result';return render()}shell(`${header('result')}<p class="eyebrow">TODAY'S OPTION</p><article class="detail-card"><div class="detail-meta"><span class="tag">${w.duration}</span><span class="tag coral">${w.intensity}强度</span><span class="tag sage">${w.equipment}</span></div><h1>${w.title}</h1><p>${w.desc}</p><h2 class="section-title">今天会做什么</h2><ol class="steps">${w.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="safety-note"><strong>安全提醒：</strong>${w.safe}</div><button class="button button-primary" data-a="done">完成训练，留下反馈</button><button class="button button-quiet" data-a="result">换一个训练</button></article>`)}
  function feedback(){const w=workouts.find(x=>x.id===S.workout);const fields=[['completion','今天是否完成？',['完成','完成一部分','没有完成']],['afterFeeling','训练后感觉？',['更有精神','正常','更累','有不适']],['recommendationAccuracy','这个推荐准吗？',['很准','还可以','不太准']]];shell(`${header('workout')}<p class="eyebrow">CLOSE THE LOOP</p><h1 class="page-title">做完就很好。<br>听听身体怎么说。</h1><p class="form-intro">${w.title} · ${w.duration}</p><form id="feedback-form">${fields.map(f=>field(f,S.feedback,'feedback')).join('')}<div class="question"><label class="question-label">想补充什么？<span class="question-hint">可选，只保存在本机</span><textarea name="note" rows="4" maxlength="300" placeholder="例如：下蹲时膝盖有点紧，明天想安排散步。">${esc(S.feedback.note||'')}</textarea></label></div><button class="button button-primary">保存反馈</button></form>`)}
  function records(){const c=read(K.c,[]).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,7),w=read(K.w,[]).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));if(!c.length)return shell(`${header()}<p class="eyebrow">YOUR BODY, YOUR PATTERN</p><h1 class="page-title">训练不是每天<br>都一样强。</h1><div class="empty">这里会慢慢长出你的身体记录。<br><button class="text-button" data-a="nav" data-s="checkin">从今天的 1 分钟打卡开始 →</button></div>`);const completed=w.filter(x=>x.completion==='完成').length,recovery=c.filter(x=>x.dayType==='恢复日').length; shell(`${header()}<p class="eyebrow">YOUR BODY, YOUR PATTERN</p><h1 class="page-title">训练不是每天<br>都一样强。</h1><p class="form-intro">持续认识自己的身体，就是一种进步。</p><section class="record-summary"><div class="metric"><strong>${c.length}</strong><span>最近记录天数</span></div><div class="metric"><strong>${completed}</strong><span>完成训练次数</span></div><div class="metric"><strong>${recovery}</strong><span>恢复日次数</span></div></section><h2 class="section-title">最近 7 天</h2><section class="timeline">${c.map(x=>{const l=w.find(i=>i.date===x.date);return `<article class="timeline-item"><div class="date-box">${date(x.date)}</div><div><h4>${x.dayType} <span class="tag">${x.score} 分</span></h4><p>睡眠${x.sleep} · 精力${x.energy} · 疼痛${x.pain}${l?` · 训练${l.completion}`:' · 暂未反馈'}</p></div></article>`}).join('')}</section>${w.length?`<h2 class="section-title" style="margin-top:25px">最近训练反馈</h2><section class="timeline">${w.slice(0,3).map(l=>`<article class="timeline-item"><div class="date-box">${date(l.date)}</div><div><h4>${esc(l.workoutTitle)}</h4><p>${l.completion} · ${l.afterFeeling} · 推荐${l.recommendationAccuracy}</p></div></article>`).join('')}</section>`:''}`)}
  function privacy(){shell(`${header()}<p class="eyebrow">PRIVACY, WITHOUT FINE PRINT</p><h1 class="page-title">你的身体数据，<br>只属于你。</h1><section class="detail-card"><h2 class="section-title">隐私说明</h2><p>女训 MVP 默认不需要登录。你的基础信息、身体状态、经期状态和训练反馈仅保存在当前浏览器的 localStorage 中。</p><p>本 MVP 不上传数据，不接入广告 SDK，也不把身体状态用于广告推荐。你可以随时清除本地数据。</p><p>本产品提供训练参考，不提供医疗诊断。如果你有明显疼痛、异常出血、长期月经紊乱、严重不适或其他健康问题，请咨询医生。</p><div class="callout warning"><strong>关于 AI：</strong>只有在运营台填写自己的服务端 AI 地址后，提问内容才会发送至该地址；默认演示模式不会出站发送数据。</div><button class="button button-danger" data-a="clear">清除本机全部数据</button></section>`)}

  function events(){const a=read(K.e,[]),demo=[{at:now(),type:'system.ready',detail:'静态预览已启动',level:'info',device:'preview'},{at:new Date(Date.now()-480000).toISOString(),type:'ai.fallback',detail:'AI 服务未配置，使用本地安全回复',level:'warn',device:'preview'}];return [...a,...demo].sort((x,y)=>y.at.localeCompare(x.at)).slice(0,12)}
  function admin(){const tabs=[['overview','概览'],['users','活跃用户'],['logs','日志排查'],['load','负载与健康'],['api','AI 与 Skill']], body={overview:overview,users:users,logs:logs,load:load,api:api}[S.tab]();app.innerHTML=`<section class="admin-shell"><header class="admin-topbar"><div><div class="brand admin-brand"><span class="brand-mark">力</span>女训 <span class="tag">运营台</span></div><p>本地 MVP 管理视图 · 演示数据与当前浏览器数据分开标注</p></div><button class="button button-secondary small" data-a="user">返回女训前台 →</button></header><nav class="admin-nav">${tabs.map(t=>`<button class="${S.tab===t[0]?'active':''}" data-a="tab" data-t="${t[0]}">${t[1]}</button>`).join('')}</nav>${body}</section>`}
  function overview(){const p=read(K.p,null),c=read(K.c,[]),w=read(K.w,[]),err=events().filter(x=>x.level==='error').length;return `<p class="eyebrow">OVERVIEW · LOCAL PREVIEW</p><h1 class="page-title">今天的运营脉搏。</h1><section class="dashboard-grid"><article class="admin-metric"><span class="label">本机活跃用户</span><strong>${p?1:0}</strong><span class="trend">当前浏览器会话</span></article><article class="admin-metric"><span class="label">今日状态打卡</span><strong>${c.filter(x=>x.date===today()).length}</strong><span class="trend">本机数据</span></article><article class="admin-metric"><span class="label">完成训练</span><strong>${w.filter(x=>x.completion==='完成').length}</strong><span class="trend">累计本机记录</span></article><article class="admin-metric"><span class="label">待排查错误</span><strong>${err}</strong><span class="trend">本地事件日志</span></article></section><section class="admin-card"><h2>产品闭环</h2><p>从欢迎页到反馈，当前浏览器的漏斗显示在这里。接入事件 API 后可扩展为真实的 DAU、转化和留存数据。</p><div class="load-bars"><div class="load-row"><span>完成资料</span><div class="bar"><i style="width:${p?100:0}%"></i></div><b>${p?1:0}</b></div><div class="load-row"><span>完成打卡</span><div class="bar"><i style="width:${c.length?100:0}%"></i></div><b>${c.length}</b></div><div class="load-row"><span>训练反馈</span><div class="bar"><i style="width:${w.length?100:0}%"></i></div><b>${w.length}</b></div></div></section><section class="admin-card"><h2>上线前提醒</h2><div class="admin-note">这不是“假装有后端”：当前是可部署的静态演示壳。真实用户、服务日志和负载需由服务端 API 采集，再替换本页的本地数据适配器。AI 密钥也必须只放在服务端。</div></section>`}
  function users(){const p=read(K.p,null);return `<p class="eyebrow">USAGE · ANONYMOUS BY DESIGN</p><h1 class="page-title">谁在使用？</h1><section class="admin-card"><h2>活跃用户</h2><p>静态 MVP 只显示当前浏览器的匿名设备；不采集姓名、手机号或精确身份。接入服务端后可按匿名设备 ID 聚合 DAU / WAU。</p><div class="table-wrap"><table><thead><tr><th>匿名设备</th><th>最近活跃</th><th>年龄段</th><th>运动状态</th><th>今日阶段</th></tr></thead><tbody>${p?`<tr><td>${device}</td><td>刚刚</td><td>${esc(p.ageRange)}</td><td>${esc(p.activityLevel)}</td><td><span class="status ok">本机活跃</span></td></tr>`:'<tr><td colspan="5" class="muted">还没有本机用户资料。进入前台完成基础设置后，这里会显示匿名会话。</td></tr>'}</tbody></table></div></section><section class="admin-card"><h2>隐私边界</h2><p>真实运营统计建议只上传匿名 ID、事件、时间、版本、页面与性能指标；不上传备注文本、经期状态和原始健康描述。</p></section>`}
  function logs(){return `<p class="eyebrow">OBSERVABILITY · LOCAL EVENT STREAM</p><h1 class="page-title">问题有迹可循。</h1><section class="admin-card"><h2>最近事件</h2><p>事件记录不含训练备注和原始健康数据。真实环境可接入 Sentry、OpenTelemetry 或自建日志服务。</p><div class="table-wrap"><table><thead><tr><th>时间</th><th>级别</th><th>事件</th><th>摘要</th><th>设备</th></tr></thead><tbody>${events().map(x=>`<tr><td>${new Date(x.at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</td><td><span class="status ${x.level==='error'?'error':x.level==='warn'?'warn':'ok'}">${x.level}</span></td><td>${esc(x.type)}</td><td>${esc(x.detail)}</td><td>${esc(x.device)}</td></tr>`).join('')}</tbody></table></div></section><section class="admin-card"><h2>建议的排查字段</h2><p>请求 ID、匿名会话 ID、页面、版本号、API 状态、响应耗时、模型名称、Skill 版本、错误码。这样既能定位问题，也避免把用户身体叙述写进日志。</p></section>`}
  function load(){const a=read(K.a,{});return `<p class="eyebrow">HEALTH · CAPACITY</p><h1 class="page-title">负载先有看见，<br>再谈扩容。</h1><section class="dashboard-grid"><article class="admin-metric"><span class="label">前端资源</span><strong>OK</strong><span class="trend">静态文件可由 CDN 托管</span></article><article class="admin-metric"><span class="label">AI 服务</span><strong>${a.aiEndpoint?'API':'LOCAL'}</strong><span class="trend">${a.aiEndpoint?'待服务端健康检查':'未接入（本地回退中）'}</span></article><article class="admin-metric"><span class="label">事件队列</span><strong>0</strong><span class="trend">静态预览不出站</span></article><article class="admin-metric"><span class="label">P95 响应</span><strong>—</strong><span class="trend">接 API 后采集</span></article></section><section class="admin-card"><h2>生产环境建议阈值</h2><div class="load-bars"><div class="load-row"><span>AI 成功率</span><div class="bar"><i style="width:0%"></i></div><b>—</b></div><div class="load-row"><span>AI P95 延迟</span><div class="bar"><i style="width:0%"></i></div><b>—</b></div><div class="load-row"><span>错误率</span><div class="bar"><i style="width:0%"></i></div><b>—</b></div></div><div class="admin-note" style="margin-top:18px">建议后台服务暴露 <code>/api/admin/health</code>、<code>/metrics</code> 与结构化日志。AI 调用要有超时、限流、熔断与本地规则回退。</div></section>`}
  function api(){const a=read(K.a,{aiEndpoint:'',skillEndpoint:'',eventsEndpoint:''});return `<p class="eyebrow">INTEGRATIONS · SERVER-SIDE ONLY</p><h1 class="page-title">给 AI 与专业知识<br>留好接口。</h1><section class="admin-card"><h2>服务端接口配置</h2><p>填写你自己的后端代理地址，不是模型 API Key。前台会把“问问女训助手”发给代理；代理再调用通用模型和下一阶段的专业知识 Skill。</p><form id="api-form"><div class="config-row"><label>通用 AI 代理</label><input name="aiEndpoint" type="url" placeholder="https://api.example.com/api/ai/chat" value="${esc(a.aiEndpoint||'')}"><span class="tiny">POST</span></div><div class="config-row"><label>专业知识 Skill</label><input name="skillEndpoint" type="url" placeholder="https://api.example.com/api/skills/womens-training" value="${esc(a.skillEndpoint||'')}"><span class="tiny">预留</span></div><div class="config-row"><label>匿名事件采集</label><input name="eventsEndpoint" type="url" placeholder="https://api.example.com/api/events" value="${esc(a.eventsEndpoint||'')}"><span class="tiny">预留</span></div><button class="button button-primary small">保存接口配置</button></form></section><section class="admin-card"><h2>前台 AI 请求约定</h2><div class="admin-note"><code>POST /api/ai/chat</code><br>请求：<code>message</code>、匿名 <code>context</code>（资料、打卡、推荐）与可选 <code>skillEndpoint</code>。返回：<code>{ reply, model, traceId }</code>。后端应先应用安全规则和专业知识，再调用通用模型；失败时返回本地规则建议。</div></section>`}

  function render(){if(S.mode==='admin')return admin();({welcome,profile,checkin,result,workout,feedback,records,privacy}[S.screen]||welcome)()}
  function mode(m){S.mode=m;const u=new URL(location.href);m==='admin'?u.searchParams.set('mode','admin'):u.searchParams.delete('mode');history.replaceState({},'',u);render()}
  function validate(fields,d){const blank=fields.find(x=>x[3]?!(d[x[0]]||[]).length:!d[x[0]]);if(blank){tip(`请先完成「${blank[1].replace('？','')}」`);return false}return true}
  function saveProfile(){if(!validate(profileFields,S.profile))return;save(K.p,{...S.profile,createdAt:read(K.p,{}).createdAt||now()});eventLog('profile.saved','用户基础设置已保存');S.screen='checkin';tip('基础设置已保存在本机');render()}
  function saveCheckin(){if(!validate(checkinFields,S.checkin))return;const r=calc(S.checkin),x={date:today(),...S.checkin,score:r.score,dayType:r.dayType,createdAt:now()},a=read(K.c,[]).filter(i=>i.date!==x.date);a.unshift(x);save(K.c,a);eventLog('recommendation.created',`${r.dayType} · score=${r.score}`);S.last=r;S.screen='result';render()}
  function saveFeedback(note){if(['completion','afterFeeling','recommendationAccuracy'].some(k=>!S.feedback[k]))return tip('请先完成这 3 项反馈');const w=workouts.find(x=>x.id===S.workout),x={date:today(),workoutId:w.id,workoutTitle:w.title,...S.feedback,note:note.trim(),createdAt:now()},a=read(K.w,[]).filter(i=>!(i.date===x.date&&i.workoutId===x.workoutId));a.unshift(x);save(K.w,a);eventLog('workout.feedback_saved',`${w.id} · ${x.completion}`);S.screen='records';tip('已保存。你正在建立自己的训练节奏。');render()}
  function localAI(q,r){if(/痛|疼|不适|出血/.test(q))return '如果出现明显疼痛、异常出血或持续不适，先停止训练并咨询医生。今天优先把目标放在恢复和安全上。';if(r.dayType==='恢复日')return '你今天的恢复信号比较明确。比起安排训练部位，更适合从 8 分钟放松或轻松散步开始；做完仍不舒服就安心休息。';if(r.dayType==='降载日')return '今天可以保留动作，但把组数、重量或速度降下来。你可以先做 5 分钟热身，再判断要继续低冲击训练还是换成拉伸。';return '今天的基础状态允许训练。先用 5 分钟热身确认身体感觉；如果动作质量稳定，再完成你选的训练，不需要额外加码。'}
  async function askAI(message){const r=S.last||latest(),box=$('#ai-message'),a=read(K.a,{});if(!r||!box)return;box.textContent='正在整理今天的状态…';const context={profile:read(K.p,{}),checkin:read(K.c,[]).find(x=>x.date===today())||{},recommendation:{score:r.score,dayType:r.dayType}};if(!a.aiEndpoint){S.ai=localAI(message,r);box.textContent=S.ai;return eventLog('ai.fallback','使用本地规则回复','warn')}try{const res=await fetch(a.aiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,context,skillEndpoint:a.skillEndpoint||undefined,channel:'training-assistant'})});if(!res.ok)throw Error(`HTTP ${res.status}`);const data=await res.json();if(!data.reply)throw Error('missing reply');S.ai=data.reply;box.textContent=data.reply;eventLog('ai.reply',data.traceId||'AI reply received')}catch(err){S.ai=`${localAI(message,r)}（AI 服务暂不可用，已切换为本地建议。）`;box.textContent=S.ai;eventLog('ai.error',err.message,'error')}}
  app.addEventListener('click',e=>{const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a;if(a==='pick'){const d=b.dataset.kind==='profile'?S.profile:b.dataset.kind==='checkin'?S.checkin:S.feedback,k=b.dataset.k,v=b.dataset.v,f=[...profileFields,...checkinFields].find(x=>x[0]===k);if(f&&f[3]){const old=d[k]||[];if(!old.includes(v)&&old.length>=3)return tip('训练目标最多选择 3 项');d[k]=old.includes(v)?old.filter(x=>x!==v):[...old,v]}else d[k]=v;return render()}if(a==='start'){S.screen=read(K.p,null)?'checkin':'profile';render()}if(a==='go'){S.screen=b.dataset.s;render()}if(a==='home'){S.screen='welcome';render()}if(a==='result'){S.screen='result';render()}if(a==='workout'){S.workout=b.dataset.id;S.screen='workout';render()}if(a==='done'){S.feedback={};S.screen='feedback';render()}if(a==='nav'){S.screen=b.dataset.s==='result'&&!latest()?'checkin':b.dataset.s;render()}if(a==='admin')mode('admin');if(a==='user')mode('user');if(a==='tab'){S.tab=b.dataset.t;render()}if(a==='clear'&&confirm('确定清除本机中的女训资料、状态记录和训练反馈吗？此操作不可恢复。')){Object.values(K).forEach(k=>localStorage.removeItem(k));S={...S,screen:'welcome',profile:{},checkin:{},feedback:{},workout:null,last:null};tip('本地数据已清除');render()}});
  app.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='profile-form')saveProfile();if(e.target.id==='checkin-form')saveCheckin();if(e.target.id==='feedback-form')saveFeedback(e.target.elements.note.value);if(e.target.id==='api-form'){save(K.a,{aiEndpoint:e.target.elements.aiEndpoint.value.trim(),skillEndpoint:e.target.elements.skillEndpoint.value.trim(),eventsEndpoint:e.target.elements.eventsEndpoint.value.trim()});eventLog('admin.config_saved','AI integration configuration updated');tip('接口配置已保存到本机');render()}if(e.target.id==='ai-form'){const q=e.target.elements.message.value.trim();if(!q)return tip('写下你的问题，再问问助手吧');askAI(q);e.target.reset()}});
  window.nvX={calculateRecommendation:calc,workouts};render();
})();

