/* 女训 MVP 0.2：纯前端、本地优先。周期阶段仅供训练参考，不是医学或激素诊断。 */
(() => {
'use strict';
const STORAGE_KEYS={USER_PROFILE:'nvxun_userProfile',DAILY_CHECKINS:'nvxun_dailyCheckins',WORKOUT_LOGS:'nvxun_workoutLogs',STRENGTH_LOGS:'nvxun_strengthWorkoutLogs',BODY_METRICS:'nvxun_bodyMetricLogs',ADMIN_AUTH:'nvxun_adminAuth',EVENTS:'nvxun_events',DEVICE:'nvxun_deviceId'};
const LEGACY={profile:'nvx.userProfile',checkins:'nvx.dailyCheckins',workouts:'nvx.workoutLogs',events:'nvx.events',device:'nvx.deviceId'};
const app=document.querySelector('#app'),toastEl=document.querySelector('#toast'),ADMIN_PASSWORD='nvxun2026';
const today=()=>new Date().toISOString().slice(0,10),now=()=>new Date().toISOString();
const read=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const dateLabel=v=>{const d=new Date(`${v}T12:00:00`);return `${d.getMonth()+1}月${d.getDate()}日`};
const newest=(a,k='createdAt')=>[...a].sort((x,y)=>String(y[k]||y.date).localeCompare(String(x[k]||x.date)));
const cycleStage=v=>['有规律月经','有月经，但不太规律','经前反应明显'].includes(v);
const regular=p=>['每周规律运动 3 次及以上','有稳定力量训练经验'].includes(p?.trainingLevel);
const beginner=p=>['几乎没接触过健身','健身初期，偶尔练'].includes(p?.trainingLevel);
function migrate(){
 if(!localStorage.getItem(STORAGE_KEYS.USER_PROFILE)){const old=read(LEGACY.profile,null);if(old){const levels={'几乎不运动，但想开始':'几乎没接触过健身','偶尔运动，难以坚持':'健身初期，偶尔练','每周运动 1—2 次':'每周规律运动 1—2 次','每周运动 3 次及以上':'每周规律运动 3 次及以上','曾经规律运动，现在中断了':'健身初期，偶尔练','正在恢复训练':'健身初期，偶尔练'};const goals={'变强壮 / 有力量':'提升力量','减脂塑形':'减脂','改善疲劳和精力':'改善睡眠和疲劳','改善经前/经期状态':'改善经期/经前状态','减少疼痛或不适':'保持长期运动状态'};save(STORAGE_KEYS.USER_PROFILE,{...old,trainingLevel:old.trainingLevel||levels[old.activityLevel]||'健身初期，偶尔练',trainingPlace:old.trainingPlace==='健身房'?'健身房器械':old.trainingPlace||'都可以',goals:(old.goals||[]).map(x=>goals[x]||x).slice(0,3),migratedAt:now()});}}
 if(!localStorage.getItem(STORAGE_KEYS.DAILY_CHECKINS))save(STORAGE_KEYS.DAILY_CHECKINS,read(LEGACY.checkins,[]));
 if(!localStorage.getItem(STORAGE_KEYS.WORKOUT_LOGS))save(STORAGE_KEYS.WORKOUT_LOGS,read(LEGACY.workouts,[]));
 if(!localStorage.getItem(STORAGE_KEYS.EVENTS))save(STORAGE_KEYS.EVENTS,read(LEGACY.events,[]));
 if(!localStorage.getItem(STORAGE_KEYS.DEVICE))localStorage.setItem(STORAGE_KEYS.DEVICE,localStorage.getItem(LEGACY.device)||`local-${Math.random().toString(36).slice(2,8)}`);
}migrate();
const profileFields=[
 ['ageRange','你的年龄段',['18—24 岁','25—34 岁','35—44 岁','45—54 岁','55 岁以上','不想回答']],
 ['bodyStage','你现在的身体阶段',['有规律月经','有月经，但不太规律','经前反应明显','正在经历或接近围绝经期','已经绝经','不确定 / 不想回答']],
 ['trainingLevel','你的训练水平',['几乎没接触过健身','健身初期，偶尔练','每周规律运动 1—2 次','每周规律运动 3 次及以上','有稳定力量训练经验']],
 ['goals','你想从训练中获得什么？',['建立运动习惯','减脂','增肌','提升力量','改善经期/经前状态','改善睡眠和疲劳','增加肌肉，预防衰老','保持长期运动状态'],true,'最多选择 3 项'],
 ['trainingPlace','你更常在哪里训练？',['居家无器械','居家小器械','健身房器械','自由重量训练','都可以']]
];
const checkinFields=[
 ['sleep','昨晚睡眠',['好','一般','差']],['energy','今日精力',['高','中','低']],['pain','疼痛或不适',['无','轻微','明显']],['soreness','肌肉酸痛 / 关节不适',['无','轻微','明显']],['stressMood','情绪 / 压力',['稳定','有点压力','压力很大 / 情绪波动明显']],['cycleStatus','月经 / 经前状态',['非经期，状态稳定','经期第 1—2 天','经期第 3 天及以后','经前疲劳 / PMS 明显','周期不规律 / 不确定','不适用']],['trainingIntent','今天的训练意愿',['很想练','可以练','不太想练','只想轻轻动一下']]
];
const actions=[
{id:'dead_bug',name:'死虫式',category:'核心稳定',targetMuscles:['核心','腹部'],difficulty:'入门',suitable:'初学者、想提升核心控制的人',description:'仰卧时保持躯干稳定，交替伸展对侧手脚。',steps:['仰卧，双膝屈曲 90 度，双手向上。','轻轻收紧腹部，让腰背保持自然稳定。','缓慢伸出对侧手和腿，再回到起点。'],mistakes:['腰部明显拱起','动作太快','憋气'],safety:'腰部不适时缩小动作幅度，始终保持顺畅呼吸。'},
{id:'bird_dog',name:'鸟狗式',category:'核心稳定',targetMuscles:['核心','臀部','背部'],difficulty:'入门',suitable:'初学者、久坐或需要低冲击训练的人',description:'四点跪姿交替伸展对侧手脚，练习躯干抗旋转。',steps:['双手在肩下、双膝在髋下。','慢慢伸出对侧手和腿，骨盆保持平稳。','停一秒后控制回位，换边。'],mistakes:['腰部塌陷','骨盆左右摇晃','抬得过高'],safety:'手腕或膝盖不舒服时可垫软垫并缩短停留时间。'},
{id:'glute_bridge',name:'臀桥',category:'臀腿',targetMuscles:['臀大肌','后侧链'],difficulty:'入门',suitable:'初学者、想激活臀部或练习髋伸的人',description:'仰卧抬髋，感受臀部发力。',steps:['仰卧屈膝，脚掌稳定踩地。','呼气时推地抬髋，身体接近一条直线。','在顶端轻轻收臀，再缓慢下放。'],mistakes:['用腰顶起','双膝内扣','脚离臀太远'],safety:'腰部感觉不适时减少高度，先确认臀部发力。'},
{id:'chair_squat',name:'椅子辅助深蹲',category:'下肢',targetMuscles:['大腿','臀部'],difficulty:'入门',suitable:'刚开始练下肢、担心深蹲动作的人',description:'借助椅子练习下蹲和站起的控制。',steps:['站在稳固椅子前，双脚与髋同宽。','屈髋屈膝，轻碰椅面后推地站起。','膝盖方向跟随脚尖。'],mistakes:['膝盖明显内扣','快速坐下','脚跟抬起'],safety:'使用不会滑动的椅子；膝关节疼痛时停止。'},
{id:'wall_pushup',name:'墙壁俯卧撑',category:'上肢推',targetMuscles:['胸部','肩部','三头肌'],difficulty:'入门',suitable:'上肢力量初学者',description:'借墙面练习推的模式，难度比地面俯卧撑低。',steps:['双手撑墙，身体形成一条斜线。','弯曲手肘，胸口靠近墙面。','推回起点，不耸肩。'],mistakes:['腰部塌陷','耸肩','手肘张得过开'],safety:'手腕、肩部有不适时缩短幅度或先休息。'},
{id:'plank',name:'平板支撑',category:'核心稳定',targetMuscles:['核心','肩部'],difficulty:'基础',suitable:'想提升躯干稳定的人',description:'用前臂或双手支撑，维持全身稳定。',steps:['前臂在肩下，双脚向后伸。','轻收腹和臀部，让身体成直线。','平稳呼吸，达到舒适时长即可。'],mistakes:['塌腰','耸肩','屏住呼吸'],safety:'腰背不适时可改跪姿平板支撑。'},
{id:'cat_cow',name:'猫牛式',category:'活动度',targetMuscles:['脊柱','背部'],difficulty:'入门',suitable:'恢复日、经期舒缓、久坐后',description:'配合呼吸温和活动脊柱。',steps:['四点跪姿，手在肩下。','吸气轻轻延展胸口和尾骨。','呼气缓慢拱背，感受背部展开。'],mistakes:['动作过猛','把活动都放在腰部'],safety:'只在舒适范围内活动，疼痛时停止。'},
{id:'child_pose',name:'婴儿式',category:'恢复',targetMuscles:['背部','髋部'],difficulty:'入门',suitable:'恢复日、压力大、睡前放松',description:'温和放松背部和髋部的停留姿势。',steps:['跪姿坐向脚跟，双手向前伸。','额头轻放垫面或枕头。','用慢呼吸放松肩颈和背部。'],mistakes:['强行压低身体','憋气'],safety:'膝盖不舒服时可在臀部或膝下垫枕。'},
{id:'rdl',name:'罗马尼亚硬拉',category:'下肢拉',targetMuscles:['臀部','腘绳肌','后侧链'],difficulty:'进阶',suitable:'有基础的自由重量训练者',description:'以髋主导的后侧链训练动作。',steps:['双脚与髋同宽，器械贴近大腿。','臀部向后送，保持背部中立。','感到大腿后侧拉伸后，用臀部发力站起。'],mistakes:['弓背','把重量离身体太远','下放过深失去控制'],safety:'先用轻重量学习髋铰链；腰背疼痛时不要继续加重。'},
{id:'squat',name:'深蹲',category:'下肢',targetMuscles:['股四头肌','臀部'],difficulty:'基础',suitable:'下肢力量训练者',description:'屈髋屈膝完成的基础下肢模式。',steps:['双脚站稳，脚尖自然朝前。','吸气下蹲，膝盖跟随脚尖。','推地站起，保持躯干稳定。'],mistakes:['膝盖内扣','脚跟抬起','塌腰'],safety:'从合适的深度开始；明显膝、髋、腰痛时停止。'},
{id:'lat_pulldown',name:'高位下拉',category:'上肢拉',targetMuscles:['背阔肌','上背'],difficulty:'基础',suitable:'健身房器械训练者',description:'利用器械练习垂直拉的动作。',steps:['坐稳并固定大腿，握住横杆。','肩胛先轻轻下沉。','将横杆拉向上胸，控制回放。'],mistakes:['身体大幅后仰','耸肩','借力甩动'],safety:'选择可以全程控制的重量，肩部夹痛时停止。'},
{id:'seated_row',name:'坐姿划船',category:'上肢拉',targetMuscles:['上背','背阔肌'],difficulty:'基础',suitable:'健身房器械训练者',description:'练习水平拉，帮助建立背部控制。',steps:['坐稳，胸口自然打开。','先让肩胛轻轻向后下方移动。','将把手拉向腹部，再慢慢回位。'],mistakes:['耸肩','含胸圆背','后仰借力'],safety:'不要追求过大幅度；腰背不适时减轻重量。'}
];
const workouts=[
{id:'starter_strength_15',title:'15 分钟新手安全力量',duration:'15 分钟',minutes:15,intensity:'低',equipment:'无器械',type:'全身',audience:'新手',desc:'适合想开始力量训练、又担心受伤的今天。',steps:['热身：原地踏步 2 分钟','椅子辅助深蹲 8 次 × 2 组','墙壁俯卧撑 8 次 × 2 组','臀桥 10 次 × 2 组','死虫式 8 次 × 2 组','拉伸放松 2 分钟'],actionIds:['chair_squat','wall_pushup','glute_bridge','dead_bug'],videoCategories:['力量 / 无氧'],safe:'动作过程中如果出现明显疼痛，请停止。'},
{id:'whole_strength_20',title:'20 分钟全身力量',duration:'20 分钟',minutes:20,intensity:'中',equipment:'无器械',type:'全身',audience:'基础',desc:'一次稳稳完成的居家力量练习，兼顾下肢、上肢与核心。',steps:['动态热身 3 分钟','深蹲 10 次 × 3 组','俯身划船动作模拟 10 次 × 3 组','俯卧撑或跪姿俯卧撑 8 次 × 2 组','臀桥 12 次 × 3 组','平板支撑 20 秒 × 2 组','放松 2 分钟'],actionIds:['squat','glute_bridge','plank'],videoCategories:['力量 / 无氧'],safe:'保持动作可控；腰背有不适时减少幅度。'},
{id:'advanced_strength_25',title:'25 分钟全身力量进阶',duration:'25 分钟',minutes:25,intensity:'中高',equipment:'无器械',type:'全身',audience:'进阶',desc:'适合状态不错时，把力量训练做得扎实一点。',steps:['热身 5 分钟','深蹲 12 次 × 3 组','反向弓步 8 次 × 3 组','俯卧撑 8 次 × 3 组','臀桥单腿变化 8 次 × 2 组','平板支撑 30 秒 × 3 组','放松 3 分钟'],actionIds:['squat','glute_bridge','plank'],videoCategories:['力量 / 无氧'],safe:'动作质量优先。关节疼痛、头晕或异常不适时立即停止。'},
{id:'low_impact_20',title:'20 分钟低冲击训练',duration:'20 分钟',minutes:20,intensity:'低',equipment:'无器械',type:'有氧',audience:'恢复 / 新手',desc:'保留训练节奏，同时对恢复更友好。',steps:['关节活动 3 分钟','低冲击开合步 45 秒 × 3 组','半程深蹲 10 次 × 2 组','站姿提膝 45 秒 × 2 组','鸟狗式 8 次 × 2 组','拉伸 4 分钟'],actionIds:['chair_squat','bird_dog'],videoCategories:['趣味居家有氧'],safe:'全程保持可以正常说话的强度；不舒服就放慢或改成散步。'},
{id:'period_relief_10',title:'10 分钟经期舒缓',duration:'10 分钟',minutes:10,intensity:'很低',equipment:'无器械',type:'恢复',audience:'经期 / 恢复',desc:'轻柔活动身体，今天只需要照顾好自己。',steps:['腹式呼吸 2 分钟','猫牛式 1 分钟','婴儿式停留 1 分钟','仰卧抱膝 1 分钟','坐姿前屈 1 分钟','轻柔髋部活动 2 分钟','放松呼吸 2 分钟'],actionIds:['cat_cow','child_pose'],videoCategories:['瑜伽 / 拉伸'],safe:'如果疼痛明显或流血量异常，建议休息，不强行训练。'},
{id:'sleep_reset_8',title:'8 分钟睡前放松',duration:'8 分钟',minutes:8,intensity:'很低',equipment:'无器械',type:'恢复',audience:'恢复',desc:'把训练目标换成放松和恢复，也是一种完成。',steps:['慢呼吸 2 分钟','颈肩放松 1 分钟','胸椎旋转 1 分钟','腿后侧拉伸 1 分钟','靠墙抬腿 2 分钟','安静呼吸 1 分钟'],actionIds:['child_pose'],videoCategories:['冥想 / 放松'],safe:'动作只做到舒适范围，不需要追求拉伸幅度。'},
{id:'walk_stretch_30',title:'30 分钟快走 + 拉伸',duration:'30 分钟',minutes:30,intensity:'低',equipment:'户外',type:'有氧',audience:'恢复 / 减脂',desc:'不想正式训练时，用一段快走延续和身体的连接。',steps:['轻松走 5 分钟','快走 20 分钟','小腿、臀腿、肩颈拉伸 5 分钟'],actionIds:['child_pose'],videoCategories:['趣味居家有氧'],safe:'以能说完整句子的速度走；天气或身体不适时改为室内轻活动。'},
{id:'core_stability_15',title:'15 分钟核心稳定',duration:'15 分钟',minutes:15,intensity:'低中',equipment:'无器械',type:'核心',audience:'基础',desc:'低冲击地练习稳定和控制，适合想保持节奏的今天。',steps:['热身 2 分钟','死虫式 8 次 × 2 组','鸟狗式 8 次 × 2 组','侧桥 15 秒 × 2 组','臀桥 12 次 × 2 组','拉伸 3 分钟'],actionIds:['dead_bug','bird_dog','glute_bridge'],videoCategories:['力量 / 无氧'],safe:'腰部不适时缩短动作范围，始终保持顺畅呼吸。'},
{id:'fun_cardio_20',title:'20 分钟趣味居家有氧',duration:'20 分钟',minutes:20,intensity:'中低',equipment:'无器械',type:'有氧',audience:'减脂 / 想动一动',desc:'用低门槛有氧把心情和身体一起带动起来。',steps:['热身走步 3 分钟','低冲击律动 4 分钟','间歇踏步 4 分钟','侧向移动与提膝 4 分钟','轻松走步与拉伸 5 分钟'],actionIds:[],videoCategories:['趣味居家有氧'],safe:'以舒适、可说话的强度为准；头晕或疼痛时停止。'},
{id:'gym_push_45',title:'Push 推训练',duration:'45 分钟',minutes:45,intensity:'中高',equipment:'健身房器械 / 自由重量',type:'Push',audience:'规律力量训练者',desc:'胸、肩、三头为主的力量训练，适合状态稳定的正常或冲刺日。',steps:['热身 5 分钟','哑铃卧推或器械推胸 8—10 次 × 4 组','哑铃肩推或器械肩推 8—10 次 × 3 组','上斜卧推或俯卧撑 10 次 × 3 组','侧平举 12—15 次 × 3 组','绳索下压或臂屈伸 10—12 次 × 3 组','拉伸放松 5 分钟'],actionIds:['wall_pushup'],videoCategories:['力量 / 无氧'],safe:'保留 1—3 次余力，不需要练到力竭。',deload:'重量降低 10—20%，每个动作减少 1 组，不做力竭。'},
{id:'gym_pull_45',title:'Pull 拉训练',duration:'45 分钟',minutes:45,intensity:'中高',equipment:'健身房器械 / 自由重量',type:'Pull',audience:'规律力量训练者',desc:'背、二头和后链为主的力量训练，适合状态稳定的正常或冲刺日。',steps:['热身 5 分钟','高位下拉 8—10 次 × 4 组','坐姿划船 8—10 次 × 4 组','哑铃划船 10 次 × 3 组','面拉 12—15 次 × 3 组','二头弯举 10—12 次 × 3 组','拉伸放松 5 分钟'],actionIds:['lat_pulldown','seated_row'],videoCategories:['力量 / 无氧'],safe:'动作中避免耸肩和借力甩动，始终保持重量可控。',deload:'重量降低 10—20%，减少组数，保留动作控制。'},
{id:'gym_legs_50',title:'Legs 腿臀训练',duration:'50 分钟',minutes:50,intensity:'中高',equipment:'健身房器械 / 自由重量',type:'Legs',audience:'规律力量训练者',desc:'臀、腿和核心为主的训练，适合身体状态好的日子。',steps:['热身 8 分钟','深蹲或腿举 8—10 次 × 4 组','罗马尼亚硬拉 8—10 次 × 3 组','臀推 8—10 次 × 4 组','保加利亚分腿蹲 8 次 × 3 组','腿弯举 10—12 次 × 3 组','小腿提踵 12—15 次 × 3 组','拉伸放松 5 分钟'],actionIds:['squat','rdl'],videoCategories:['力量 / 无氧'],safe:'不冲重量；膝、髋、腰有疼痛时停止并评估。',deload:'不冲重量，减少深蹲/硬拉强度，增加热身和拉伸。'},
{id:'regular_deload_35',title:'规律训练者降载训练',duration:'35 分钟',minutes:35,intensity:'低中',equipment:'健身房器械 / 自由重量',type:'降载',audience:'规律训练者',desc:'在经前疲劳、睡眠差或压力大时，保留训练节奏但降低恢复压力。',steps:['热身 8 分钟','选择当天原计划动作 3—4 个','重量降低 10—20%','每个动作完成 2—3 组','RPE 控制在 6—7','拉伸放松 8 分钟'],actionIds:['squat','rdl','lat_pulldown'],videoCategories:['瑜伽 / 拉伸'],safe:'今天不需要 PR；如果疼痛明显，改为恢复日。'}
];
const videos=[
{id:'monana_yoga',title:'经期舒缓与温和拉伸',creator:'Monana瑜伽',platform:'B站',category:'瑜伽 / 拉伸',suitableFor:['经期舒缓','拉伸','恢复日'],description:'适合想用温和活动放松身体的恢复日。',url:''},
{id:'strength_follow',title:'基础力量与无氧动作跟练',creator:'偶不偶买器',platform:'B站',category:'力量 / 无氧',suitableFor:['力量训练','动作跟练','新手'],description:'适合把基础动作节奏和发力感练得更熟。',url:''},
{id:'relaxed_rachel',title:'睡前冥想与放松练习',creator:'RelaxedRachel瑞秋',platform:'B站',category:'冥想 / 放松',suitableFor:['睡眠差','压力大','恢复日'],description:'适合在压力大、情绪起伏或睡前需要放松时使用。',url:''},
{id:'aurora_cardio',title:'低门槛居家有氧',creator:'欧阳春晓Aurora',platform:'B站',category:'趣味居家有氧',suitableFor:['减脂','想动一动','居家'],description:'适合想出汗、又不想做复杂器械训练的日子。',url:''},
{id:'april_cardio',title:'居家有氧跟练',creator:'韩小囡AprilHan',platform:'B站',category:'趣味居家有氧',suitableFor:['减脂','情绪调节','居家'],description:'适合用有节奏的活动找回训练心情。',url:''},
{id:'lelepop_cardio',title:'有氧舞长跟练',creator:'LELEPOP 有氧舞合集',platform:'B站',category:'趣味居家有氧',suitableFor:['居家有氧','减脂','投屏'],description:'适合在家跟练、想把训练做得更有趣的时候。',url:''}
];
const copy={
'冲刺日':{tone:'sprint',title:'今天是冲刺日',explain:'你的睡眠、精力和训练意愿都不错，身体目前适合承受更高质量的训练。',advice:'可以把训练做扎实一点，但不需要为了证明自己而硬冲；动作质量优先。',encourage:'状态好的时候，把训练做扎实，就是长期变强的底气。'},
'常规日':{tone:'regular',title:'今天是常规日',explain:'你的整体状态稳定，适合完成一次正常训练。保持节奏，就是有效训练。',advice:'选择一套中等强度训练，完成后记录身体感觉。',encourage:'长期训练不是每天都冲，而是大多数日子都能稳稳出现。'},
'降载日':{tone:'deload',title:'今天是降载日',explain:'今天的恢复压力更高，不适合硬冲。降低重量、减少组数，也是在保留长期训练节奏。',advice:'把目标从突破换成维持：练得轻一点、慢一点、稳一点。',encourage:'降低强度不是退步，是更聪明地长期变强。'},
'恢复日':{tone:'recovery',title:'今天是恢复日',explain:'你的身体正在发出需要恢复的信号。轻活动、拉伸、散步或认真休息都算在训练计划里。',advice:'如果有明显疼痛、异常不适或持续不适，请优先休息，必要时咨询医生。',encourage:'休息不是中断训练，而是训练计划的一部分。'}
};
const state={mode:location.hash==='#/admin'?'admin':'user',screen:'welcome',libraryTab:'workouts',recordTab:'state',adminTab:'overview',profile:{...read(STORAGE_KEYS.USER_PROFILE,{})},checkin:{},feedback:{},strength:{durationMinutes:'',exercises:[{name:'',weight:'',reps:'',sets:'',rpe:''}],note:''},workoutId:null,actionId:null,last:null};
function eventLog(type,detail='',level='info'){const a=read(STORAGE_KEYS.EVENTS,[]);a.unshift({id:`evt-${Date.now()}`,at:now(),type,detail,level,device:localStorage.getItem(STORAGE_KEYS.DEVICE)});save(STORAGE_KEYS.EVENTS,a.slice(0,80));}
function tip(message){toastEl.textContent=message;toastEl.classList.add('visible');clearTimeout(tip.t);tip.t=setTimeout(()=>toastEl.classList.remove('visible'),2600);}
function estimateCyclePhase(profile){
 const supplied=Array.isArray(profile?.periodStartDates)?profile.periodStartDates:String(profile?.periodStartDates||'').split(/[\n,，\s]+/).filter(Boolean);const dates=supplied.filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x)).sort();let cycle=Number(profile?.averageCycleLength)||28;
 if(dates.length>=2){const gaps=dates.slice(1).map((x,i)=>Math.round((new Date(`${x}T12:00:00`)-new Date(`${dates[i]}T12:00:00`))/86400000)).filter(x=>x>=18&&x<=60);if(gaps.length)cycle=Math.round(gaps.reduce((a,b)=>a+b,0)/gaps.length)}
 const period=Number(profile?.averagePeriodLength)||5,start=profile?.lastPeriodStartDate||dates.at(-1);
 const unknown={cycleDay:null,phase:'不确定',phaseLabel:'周期阶段暂不确定',confidence:'低',explanation:'目前周期信息不足或波动较大，我们不会强行判断激素阶段。今天将主要根据睡眠、精力、疼痛和训练意愿给出建议。',cycleLength:cycle,periodLength:period};
 if(!start||['很不规律','不确定'].includes(profile?.periodRegularity))return unknown;const elapsed=Math.floor((new Date(`${today()}T12:00:00`)-new Date(`${start}T12:00:00`))/86400000);if(!Number.isFinite(elapsed)||elapsed<0)return unknown;
 const cycleDay=elapsed%cycle+1,ovu=Math.max(period+2,cycle-14),toNext=cycle-cycleDay,confidence=dates.length>=2&&profile.periodRegularity==='比较规律'?'中高':'中';let phase='黄体期',phaseLabel='预计黄体期',explanation='你当前大致处于黄体期。部分人会感觉恢复变慢、疲劳或情绪波动；今天仍以睡眠、压力和疼痛作为训练强度的主要依据。';
 if(cycleDay<=period){phase='月经期';phaseLabel='预计月经期';explanation='你当前大致处于月经期。出血、疼痛、疲劳或想休息都很常见，今天的训练建议会更看重疼痛和精力。'}
 else if(cycleDay<ovu-2){phase='卵泡期';phaseLabel='预计卵泡期（低激素期）';explanation='你当前大致处于卵泡期。很多人在这个阶段精力和训练状态更稳定，但仍要结合睡眠、压力和疼痛判断。'}
 else if(cycleDay<=ovu+2){phase='排卵窗口';phaseLabel='预计接近排卵窗口';explanation='你当前可能接近排卵窗口。状态好时可以正常训练；若有关节不适或疲劳，建议加强热身和动作控制。'}
 else if(toNext>=0&&toNext<=5){phase='经前期';phaseLabel='预计经前期';explanation='你当前可能接近经前期。疲劳、睡眠变差、情绪波动、腹胀或食欲变化都可能出现；训练目标可以从突破改为维持或恢复。'}
 return{cycleDay,phase,phaseLabel,confidence,explanation,cycleLength:cycle,periodLength:period,daysToNext:toNext};
}
function calculateRecommendation(c,profile={}){let score=5;const p={sleep:{'好':2,'一般':0,'差':-2},energy:{'高':2,'中':0,'低':-2},pain:{'无':1,'轻微':-1,'明显':-3},soreness:{'无':1,'轻微':-1,'明显':-3},stressMood:{'稳定':1,'有点压力':-1,'压力很大 / 情绪波动明显':-2},cycleStatus:{'非经期，状态稳定':1,'经期第 1—2 天':-2,'经期第 3 天及以后':-1,'经前疲劳 / PMS 明显':-2,'周期不规律 / 不确定':0,'不适用':0},trainingIntent:{'很想练':2,'可以练':1,'不太想练':-1,'只想轻轻动一下':-2}};Object.entries(p).forEach(([k,v])=>score+=v[c[k]]||0);let dayType=score>=9?'冲刺日':score>=6?'常规日':score>=3?'降载日':'恢复日';
 if(c.pain==='明显')dayType='恢复日';if(c.soreness==='明显'&&dayType==='冲刺日')dayType='降载日';if(c.sleep==='差'&&c.energy==='低'&&['冲刺日','常规日'].includes(dayType))dayType='降载日';if(c.cycleStatus==='经期第 1—2 天'&&c.pain!=='无')dayType='恢复日';if(c.cycleStatus==='经前疲劳 / PMS 明显'&&c.stressMood==='压力很大 / 情绪波动明显'&&['冲刺日','常规日'].includes(dayType))dayType='降载日';if(c.cycleStatus==='经前疲劳 / PMS 明显'&&c.pain!=='明显'&&c.trainingIntent!=='只想轻轻动一下'&&dayType==='恢复日')dayType='降载日';const phase=estimateCyclePhase(profile);if(phase.phase==='经前期'&&c.sleep==='差'&&['冲刺日','常规日'].includes(dayType))dayType='降载日';return{score,dayType,copy:copy[dayType],phase};
}
function chooseWorkouts(profile,result){const find=id=>workouts.find(x=>x.id===id),goals=profile.goals||[],gym=['健身房器械','自由重量训练','都可以'].includes(profile.trainingPlace);let ids;if(result.dayType==='恢复日')ids=['period_relief_10','walk_stretch_30','sleep_reset_8'];else if(regular(profile)&&gym){if(result.dayType==='降载日')ids=['regular_deload_35','core_stability_15','walk_stretch_30'];else{const r=['gym_push_45','gym_pull_45','gym_legs_50'],i=Number(today().slice(-1))%3;ids=[r[i],r[(i+1)%3],r[(i+2)%3]]}}else if(beginner(profile))ids=result.dayType==='降载日'?['starter_strength_15','low_impact_20','sleep_reset_8']:['starter_strength_15','low_impact_20','core_stability_15'];else if(result.dayType==='降载日')ids=['low_impact_20','core_stability_15','walk_stretch_30'];else ids=['whole_strength_20','advanced_strength_25','core_stability_15'];if(goals.includes('减脂')&&result.dayType!=='恢复日'&&!regular(profile))ids[1]='fun_cardio_20';return ids.map(find).filter(Boolean)}
function reasons(profile,c,result){const r=[];if(c.sleep==='差'||c.energy==='低')r.push('睡眠和精力让今天的恢复空间变小');if(c.pain!=='无'||c.soreness==='明显')r.push('身体不适需要优先被照顾');if(c.cycleStatus.includes('经期')||c.cycleStatus.includes('经前'))r.push('你填写的周期状态也提示今天更适合灵活调整');if(result.phase.phase!=='不确定')r.push(`${result.phase.phaseLabel.replace('预计','')}只是额外的训练参考，不替代你的实际感受`);const level=profile.trainingLevel?`你的训练水平是「${profile.trainingLevel}」`:'';const goal=(profile.goals||[]).slice(0,2).join('、');return `${level}${level&&goal?'，':''}${goal?`你想关注${goal}`:''}。${r.length?r.join('；'):'今天的状态整体稳定，可以在动作质量优先的前提下完成训练。'}`}
function latest(){const a=newest(read(STORAGE_KEYS.DAILY_CHECKINS,[]),'date'),c=a.find(x=>x.date===today())||a[0];if(!c)return null;const p=read(STORAGE_KEYS.USER_PROFILE,{}),r=calculateRecommendation(c,p);return{...r,score:c.score??r.score,dayType:c.dayType||r.dayType,workouts:chooseWorkouts(p,r),checkin:c}}
const header=back=>`<header class="topbar"><div class="brand"><span class="brand-mark">力</span>女训 <span class="version-pill">0.2</span></div>${back?`<button class="icon-button" data-action="${back}" aria-label="返回">←</button>`:'<span class="top-spacer"></span>'}</header>`;
function nav(){const active=state.screen,item=(s,i,l)=>`<button class="nav-item ${active===s||(s==='library'&&active==='action')||(s==='result'&&['workout','feedback'].includes(active))?'active':''}" data-action="nav" data-screen="${s}"><b>${i}</b>${l}</button>`;return `<nav class="bottom-nav bottom-nav-five">${item('checkin','◉','今日')}${item('library','▧','训练库')}${item('videos','▷','视频跟练')}${item('records','▤','记录')}${item('privacy','□','隐私')}</nav>`}
const shell=(content,withNav=true)=>app.innerHTML=`<section class="shell">${content}${withNav?nav():''}</section>`;
function field(f,d,kind){const[k,label,options,multi,hint]=f,selected=multi?(d[k]||[]):d[k];return `<fieldset class="question"><legend>${label}${hint?`<span class="question-hint">${hint}</span>`:''}</legend><div class="choice-grid ${options.length<=4?'two':''}">${options.map(v=>`<button type="button" class="choice ${multi?'check':''} ${(multi?selected.includes(v):selected===v)?'selected':''}" data-action="pick" data-kind="${kind}" data-field="${k}" data-value="${esc(v)}"><span class="dot"></span>${esc(v)}</button>`).join('')}</div></fieldset>`}
function input(label,name,value,type='text',hint=''){return `<label class="input-field">${label}${hint?`<span>${hint}</span>`:''}<input name="${name}" type="${type}" value="${esc(value||'')}"></label>`}
function captureProfile(form=document.querySelector('#profile-form')){if(!form)return;const e=form.elements;['lastPeriodStartDate','periodRegularity','averageCycleLength','averagePeriodLength'].forEach(k=>{if(e[k])state.profile[k]=e[k].value});if(e.periodStartDates)state.profile.periodStartDates=e.periodStartDates.value.split(/[\n,，\s]+/).filter(Boolean)}
function captureFeedback(form=document.querySelector('#feedback-form')){if(form?.elements.note)state.feedback.note=form.elements.note.value}
function welcome(){shell(`${header()}<section class="hero"><p class="eyebrow">TODAY, YOUR WAY</p><h1>长寿的女人，<em>任何时候</em>都可以开始训练。</h1><div class="hero-rule"></div><p>根据你的训练水平、月经周期、睡眠、精力与疼痛，判断今天适合怎么练。</p><button class="button button-primary" data-action="start">开始今日训练判断</button><button class="button button-quiet" data-action="go" data-screen="privacy">查看隐私说明</button></section><div class="privacy-strip"><strong>默认只在本机保存。</strong> 不登录、不上传、不接广告 SDK。周期判断仅供训练参考，你随时可以清除数据。</div>`,false)}
function profile(){const cycle=cycleStage(state.profile.bodyStage);shell(`${header('home')}<p class="eyebrow">YOUR TRAINING CONTEXT</p><h1 class="page-title">让建议从你的<br>真实训练起点出发。</h1><p class="form-intro">训练水平、场景和目标会改变今天推荐的训练内容。信息只保存在当前浏览器。</p><form id="profile-form">${profileFields.map(f=>field(f,state.profile,'profile')).join('')}${cycle?`<section class="section-panel cycle-settings"><p class="eyebrow">OPTIONAL CYCLE CONTEXT</p><h2 class="section-title">周期信息（可选）</h2><p class="tiny">用于推算“预计阶段”，不用于精确判断激素水平。</p>${input('末次月经开始日期','lastPeriodStartDate',state.profile.lastPeriodStartDate,'date')}${field(['periodRegularity','最近半年周期大致规律吗？',['比较规律','有点波动','很不规律','不确定']],state.profile,'profile')}${input('平均周期长度（天）','averageCycleLength',state.profile.averageCycleLength||28,'number','从一次月经开始到下一次月经开始')}${input('平均经期长度（天）','averagePeriodLength',state.profile.averagePeriodLength||5,'number')}${input('最近半年经期开始日（可填多个）','periodStartDates',Array.isArray(state.profile.periodStartDates)?state.profile.periodStartDates.join('，'):state.profile.periodStartDates,'text','用逗号或换行分隔，例如 2026-01-03，2026-02-01')}</section>`:''}<button class="button button-primary">保存并进入今日打卡</button></form>`)}
function checkin(){if(!read(STORAGE_KEYS.USER_PROFILE,null)){state.screen='profile';return render()}shell(`${header()}<p class="eyebrow">1 MINUTE CHECK-IN · ${dateLabel(today())}</p><h1 class="page-title">今天的你，<br>状态如何？</h1><p class="form-intro">没有正确答案。按你此刻最真实的感觉选择。</p><form id="checkin-form">${checkinFields.map(f=>field(f,state.checkin,'checkin')).join('')}<button class="button button-primary">生成今日训练建议</button></form>`)}
const workoutCard=w=>`<button class="workout-card" data-action="open-workout" data-id="${w.id}"><span class="tag">${w.duration}</span><span class="tag coral">${w.intensity}强度</span><span class="tag sage">${w.type}</span><h3>${w.title} <span>→</span></h3><p>${w.desc}</p></button>`;
function videoCard(v,compact=false){const open=v.url?`<a class="button button-secondary small" target="_blank" rel="noopener" href="${esc(v.url)}">打开视频</a>`:'<button class="button button-secondary small" data-action="video-placeholder">链接待补充</button>';return `<article class="media-card ${compact?'compact':''}"><span class="tag coral">${v.platform}</span><h3>${v.title}</h3><p class="media-creator">UP 主：${v.creator}</p><p>${v.description}</p><p class="tiny">适合：${v.suitableFor.join(' · ')}</p>${open}</article>`}
function cycleCard(p){return `<section class="cycle-card"><div><p class="eyebrow">YOUR CYCLE NOTE</p><h2>${p.phaseLabel}</h2></div>${p.cycleDay?`<span class="cycle-day">第 ${p.cycleDay} 天</span>`:'<span class="cycle-day">信息不足</span>'}<p>${p.explanation}</p><small>基于你填写的周期信息推算 · 参考信心：${p.confidence}</small></section>`}
function result(){const r=state.last||latest();if(!r){state.screen='checkin';return render()}const p=read(STORAGE_KEYS.USER_PROFILE,{}),selected=r.workouts||chooseWorkouts(p,r),related=videos.filter(v=>selected.some(w=>w.videoCategories.includes(v.category))).slice(0,2),c=r.copy;shell(`${header()}<p class="eyebrow">YOUR TRAINING DECISION</p><section class="result-hero ${c.tone==='recovery'?'recovery':c.tone==='deload'?'deload':''}"><span class="result-score">状态评分 ${r.score} / 15+</span><h1>${c.title}</h1><p>${c.explain}</p></section>${cycleCard(r.phase)}<section class="section-panel"><p class="eyebrow">WHY THIS TODAY</p><h2 class="section-title">为什么今天这样推荐？</h2><p class="body-copy">${reasons(p,r.checkin,r)}</p></section><p class="recommendation-copy"><strong>今天怎么练：</strong>${c.advice}</p><div class="section-head"><h2 class="section-title">选一个现在做得到的</h2><span class="tiny">根据你的水平与场景</span></div><div class="workout-list">${selected.map(workoutCard).join('')}</div>${related.length?`<section class="recommend-video"><div class="section-head"><h2 class="section-title">视频跟练建议</h2><button class="text-button" data-action="go" data-screen="videos">全部视频 →</button></div><div class="media-list">${related.map(v=>videoCard(v,true)).join('')}</div></section>`:''}<div class="callout ${r.dayType==='恢复日'?'warning':''}"><strong>给今天的你：</strong>${c.encourage}${r.checkin.pain==='明显'?'<br><strong>安全提醒：</strong>明显疼痛或异常不适时，请停止训练并在需要时咨询医生。':''}</div>`)}
function workout(){const w=workouts.find(x=>x.id===state.workoutId);if(!w){state.screen='result';return render()}const relatedActions=actions.filter(a=>w.actionIds.includes(a.id)),related=videos.filter(v=>w.videoCategories.includes(v.category)).slice(0,2);shell(`${header('result')}<p class="eyebrow">TODAY'S OPTION · ${w.type}</p><article class="detail-card"><div class="detail-meta"><span class="tag">${w.duration}</span><span class="tag coral">${w.intensity}强度</span><span class="tag sage">${w.equipment}</span></div><h1>${w.title}</h1><p>${w.desc}</p><h2 class="section-title">今天会做什么</h2><ol class="steps">${w.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol>${w.deload?`<div class="deload-note"><strong>如果今天需要降载：</strong>${w.deload}</div>`:''}<div class="safety-note"><strong>安全提醒：</strong>${w.safe}</div>${relatedActions.length?`<section class="mini-library"><div class="section-head"><h2 class="section-title">动作说明</h2><button class="text-button" data-action="go" data-screen="library">动作库 →</button></div>${relatedActions.map(a=>`<button class="action-chip" data-action="open-action" data-id="${a.id}">${a.name}<span>${a.category}</span></button>`).join('')}</section>`:''}${related.length?`<section class="recommend-video"><h2 class="section-title">查看视频跟练</h2><div class="media-list">${related.map(v=>videoCard(v,true)).join('')}</div></section>`:''}<button class="button button-primary" data-action="complete-workout">完成训练，留下反馈</button><button class="button button-quiet" data-action="result">换一个训练</button></article>`)}
function strengthLogger(w){const show=regular(read(STORAGE_KEYS.USER_PROFILE,{}))||['Push','Pull','Legs'].includes(w.type);if(!show)return '';const rows=state.strength.exercises.map((x,i)=>`<div class="exercise-row"><div class="row-between"><strong>动作 ${i+1}</strong>${state.strength.exercises.length>1?`<button type="button" class="text-button" data-action="remove-exercise" data-index="${i}">移除</button>`:''}</div><input data-strength="name" data-index="${i}" value="${esc(x.name)}" placeholder="动作名称，例如哑铃卧推"><div class="input-grid">${['weight','reps','sets','rpe'].map(k=>`<input data-strength="${k}" data-index="${i}" inputmode="decimal" value="${esc(x[k])}" placeholder="${{weight:'重量 kg',reps:'次数 reps',sets:'组数 sets',rpe:'RPE 可选'}[k]}">`).join('')}</div></div>`).join('');return `<section class="strength-logger"><p class="eyebrow">OPTIONAL STRENGTH LOG</p><h2 class="section-title">记录重量与组数</h2><p class="tiny">适合 Push / Pull / Legs 或规律力量训练。留空也可以正常保存反馈。</p>${input('训练时长（分钟）','strengthDuration',state.strength.durationMinutes||w.minutes,'number')}${rows}<button type="button" class="button button-secondary small" data-action="add-exercise">+ 添加一个动作</button></section>`}
function feedback(){const w=workouts.find(x=>x.id===state.workoutId);if(!w){state.screen='result';return render()}const fields=[['completion','今天是否完成？',['完成','完成一部分','没有完成']],['afterFeeling','训练后感觉？',['更有精神','正常','更累','有不适']],['recommendationAccuracy','这个推荐准吗？',['很准','还可以','不太准']]];shell(`${header('workout')}<p class="eyebrow">CLOSE THE LOOP</p><h1 class="page-title">做完就很好。<br>听听身体怎么说。</h1><p class="form-intro">${w.title} · ${w.duration}</p><form id="feedback-form">${fields.map(f=>field(f,state.feedback,'feedback')).join('')}<label class="input-field">想补充什么？<span>可选，只保存在本机</span><textarea name="note" rows="4" maxlength="300" placeholder="例如：下蹲时膝盖有点紧，明天想安排散步。">${esc(state.feedback.note||'')}</textarea></label>${strengthLogger(w)}<button class="button button-primary">保存反馈</button></form>`)}
function recordTabs(){return `<div class="subnav"><button data-action="record-tab" data-tab="state" class="${state.recordTab==='state'?'active':''}">今日状态</button><button data-action="record-tab" data-tab="training" class="${state.recordTab==='training'?'active':''}">训练记录</button><button data-action="record-tab" data-tab="body" class="${state.recordTab==='body'?'active':''}">身体数据</button></div>`}
function records(){const content=state.recordTab==='body'?bodyRecords():state.recordTab==='training'?trainingRecords():stateRecords();shell(`${header()}<p class="eyebrow">YOUR BODY, YOUR PATTERN</p><h1 class="page-title">训练不是每天<br>都一样强。</h1><p class="form-intro">记录不是考核，是帮你看见自己正在怎样调整和变强。</p>${recordTabs()}${content}`)}
function stateRecords(){const c=newest(read(STORAGE_KEYS.DAILY_CHECKINS,[]),'date').slice(0,7),w=newest(read(STORAGE_KEYS.WORKOUT_LOGS,[]));if(!c.length)return `<div class="empty">这里会慢慢长出你的身体记录。<br><button class="text-button" data-action="nav" data-screen="checkin">从今天的 1 分钟打卡开始 →</button></div>`;const complete=w.filter(x=>x.completion==='完成').length,recovery=c.filter(x=>x.dayType==='恢复日').length;return `<section class="record-summary"><div class="metric"><strong>${c.length}</strong><span>最近记录天数</span></div><div class="metric"><strong>${complete}</strong><span>完成训练次数</span></div><div class="metric"><strong>${recovery}</strong><span>恢复日次数</span></div></section><h2 class="section-title">最近 7 天状态</h2><section class="timeline">${c.map(x=>{const l=w.find(i=>i.date===x.date);return `<article class="timeline-item"><div class="date-box">${dateLabel(x.date)}</div><div><h4>${x.dayType} <span class="tag">${x.score} 分</span></h4><p>睡眠${x.sleep} · 精力${x.energy} · 疼痛${x.pain} · ${x.cycleStatus}${l?` · 训练${l.completion}`:''}</p></div></article>`}).join('')}</section>`}
function trainingRecords(){const s=newest(read(STORAGE_KEYS.STRENGTH_LOGS,[])),w=newest(read(STORAGE_KEYS.WORKOUT_LOGS,[]));return `<section class="section-panel"><h2 class="section-title">力量训练记录</h2><p class="tiny">Push / Pull / Legs 及规律力量训练的重量、次数与组数会显示在这里。</p>${s.length?`<section class="timeline">${s.slice(0,7).map(l=>`<article class="timeline-item"><div class="date-box">${dateLabel(l.date)}</div><div><h4>${esc(l.workoutTitle)} <span class="tag sage">${l.workoutType}</span></h4><p>${l.durationMinutes?`${l.durationMinutes} 分钟 · `:''}${l.exercises.filter(e=>e.name).map(e=>`${e.name}${e.weight?` ${e.weight}kg`:''}${e.reps?` ×${e.reps}`:''}${e.sets?` ×${e.sets}组`:''}`).join('；')||'未填写具体动作'}</p></div></article>`).join('')}</section>`:'<div class="empty">完成一套 Push、Pull、Legs 或规律力量训练后，可以在反馈页记录重量和组数。</div>'}</section><section class="section-panel"><h2 class="section-title">最近训练反馈</h2>${w.length?`<section class="timeline">${w.slice(0,6).map(l=>`<article class="timeline-item"><div class="date-box">${dateLabel(l.date)}</div><div><h4>${esc(l.workoutTitle)}</h4><p>${l.completion} · ${l.afterFeeling} · 推荐${l.recommendationAccuracy}</p></div></article>`).join('')}</section>`:'<p class="tiny">还没有训练反馈。</p>'}</section>`}
function bodyRecords(){const m=newest(read(STORAGE_KEYS.BODY_METRICS,[]),'date'),last=m[0];return `<section class="section-panel"><p class="eyebrow">BODY METRICS · OPTIONAL</p><h2 class="section-title">身体数据记录</h2><p class="tiny">适合减脂、塑形或观察身体变化；不是每天都需要记录。</p><form id="body-form" class="body-form"><div class="input-grid two-col">${input('体重 kg','weight','','number')}${input('腰围 cm','waist','','number')}${input('臀围 cm','hip','','number')}${input('大腿围 cm','thigh','','number')}${input('睡眠时长 h','sleepHours','','number')}</div><label class="input-field">备注<textarea name="note" rows="2" placeholder="可选，例如经前一周、晨起记录"></textarea></label><button class="button button-primary">保存今天的身体数据</button></form></section>${last?`<section class="latest-metric"><h2 class="section-title">最近一次</h2><p>${dateLabel(last.date)}${last.weight?` · ${last.weight} kg`:''}${last.waist?` · 腰围 ${last.waist} cm`:''}${last.sleepHours?` · 睡眠 ${last.sleepHours} h`:''}</p></section>`:''}<section class="section-panel"><h2 class="section-title">最近 7 条</h2>${m.length?`<section class="timeline">${m.slice(0,7).map(x=>`<article class="timeline-item"><div class="date-box">${dateLabel(x.date)}</div><div><h4>${x.weight?`${x.weight} kg`:'身体数据记录'}</h4><p>${x.waist?`腰围 ${x.waist} cm · `:''}${x.hip?`臀围 ${x.hip} cm · `:''}${x.thigh?`大腿 ${x.thigh} cm · `:''}${x.sleepHours?`睡眠 ${x.sleepHours} h`:''}${x.note?` · ${esc(x.note)}`:''}</p></div></article>`).join('')}</section>`:'<p class="tiny">还没有身体数据。记录一次即可在这里看到。</p>'}</section>`}
function library(){const items=state.libraryTab==='actions'?actions:workouts;shell(`${header()}<p class="eyebrow">TRAINING LIBRARY</p><h1 class="page-title">练什么之前，<br>先知道怎么练。</h1><p class="form-intro">新手可以从动作说明开始；规律训练者也能在这里查看完整力量模板。</p><div class="subnav"><button class="${state.libraryTab==='workouts'?'active':''}" data-action="library-tab" data-tab="workouts">训练模板</button><button class="${state.libraryTab==='actions'?'active':''}" data-action="library-tab" data-tab="actions">基础动作</button></div>${state.libraryTab==='workouts'?`<div class="workout-list">${items.map(workoutCard).join('')}</div>`:`<section class="action-grid">${items.map(a=>`<button class="action-card" data-action="open-action" data-id="${a.id}"><span class="tag">${a.difficulty}</span><h3>${a.name}</h3><p>${a.category} · ${a.targetMuscles.join('、')}</p><small>${a.suitable}</small></button>`).join('')}</section>`}`)}
function movement(){const a=actions.find(x=>x.id===state.actionId);if(!a){state.screen='library';return render()}shell(`${header('back-library')}<p class="eyebrow">MOVEMENT GUIDE · ${a.category}</p><article class="detail-card"><span class="tag">${a.difficulty}</span><h1>${a.name}</h1><p>${a.description}</p><div class="action-meta"><strong>训练部位：</strong>${a.targetMuscles.join('、')}<br><strong>适合：</strong>${a.suitable}</div><h2 class="section-title">动作步骤</h2><ol class="steps">${a.steps.map(s=>`<li>${s}</li>`).join('')}</ol><section class="mistake-card"><h2 class="section-title">常见错误</h2><ul>${a.mistakes.map(x=>`<li>${x}</li>`).join('')}</ul></section><div class="safety-note"><strong>安全提示：</strong>${a.safety}</div><button class="button button-secondary" data-action="go" data-screen="videos">查看视频跟练资源</button></article>`)}
function videoLibrary(){shell(`${header()}<p class="eyebrow">VIDEO FOLLOW-ALONG</p><h1 class="page-title">需要有人带着练，<br>也完全没问题。</h1><p class="form-intro">这里只放外部资源卡片，不抓取、不嵌入未经确认的视频。链接由团队补充后会在新窗口打开。</p><section class="video-grid">${videos.map(v=>videoCard(v)).join('')}</section>`)}
function privacy(){shell(`${header()}<p class="eyebrow">PRIVACY, WITHOUT FINE PRINT</p><h1 class="page-title">你的身体数据，<br>只属于你。</h1><section class="detail-card"><h2 class="section-title">隐私说明</h2><p>女训 MVP 不需要登录。基础设置、周期信息、状态、训练反馈、力量记录和身体数据都仅保存在当前浏览器的 localStorage 中。</p><p>本版本不上传数据、不接广告 SDK、不接入 AI API，也不把身体状态用于广告推荐。</p><p>周期阶段提示基于你主动填写的信息推算，仅供训练参考，不代表激素检测或医疗判断。如果你有明显疼痛、异常出血、长期月经紊乱、严重不适或其他健康问题，请咨询医生。</p><button class="button button-danger" data-action="clear-data">清除本机全部数据</button></section>`)}
function stats(){const profile=read(STORAGE_KEYS.USER_PROFILE,null),checkins=read(STORAGE_KEYS.DAILY_CHECKINS,[]),logs=read(STORAGE_KEYS.WORKOUT_LOGS,[]),strength=read(STORAGE_KEYS.STRENGTH_LOGS,[]),metrics=read(STORAGE_KEYS.BODY_METRICS,[]);const since=new Date(Date.now()-6*86400000).toISOString().slice(0,10),distribution=['冲刺日','常规日','降载日','恢复日'].map(type=>({type,count:checkins.filter(x=>x.date>=since&&x.dayType===type).length}));return{profile,checkins,logs,strength,metrics,distribution}}
function adminLogin(){app.innerHTML=`<section class="admin-auth"><div class="admin-auth-card"><div class="brand"><span class="brand-mark">力</span>女训</div><p class="eyebrow">DEMO ADMIN</p><h1>管理入口</h1><p>这是纯前端 MVP 的演示隔离，不是生产级安全机制。</p><form id="admin-login"><label class="input-field">演示密码<input name="password" type="password" autocomplete="current-password" placeholder="输入密码"></label><button class="button button-primary">进入后台</button><p id="admin-error" class="form-error"></p></form><button class="button button-quiet" data-action="admin-logout">回到女训前台</button></div></section>`}
function admin(){if(!read(STORAGE_KEYS.ADMIN_AUTH,false))return adminLogin();const tabs=[['overview','概览'],['distribution','推荐分布'],['feedback','训练反馈'],['data','数据预览']],body={overview:adminOverview,distribution:adminDistribution,feedback:adminFeedback,data:adminData}[state.adminTab]();app.innerHTML=`<section class="admin-shell"><header class="admin-topbar"><div><div class="brand admin-brand"><span class="brand-mark">力</span>女训 <span class="tag">管理演示</span></div><p>仅用于当前浏览器的本地原型数据，不是生产级后台。</p></div><button class="button button-secondary small" data-action="admin-logout">退出后台</button></header><nav class="admin-nav">${tabs.map(([k,l])=>`<button class="${state.adminTab===k?'active':''}" data-action="admin-tab" data-tab="${k}">${l}</button>`).join('')}</nav>${body}</section>`}
function adminOverview(){const s=stats();return `<p class="eyebrow">LOCAL MVP OVERVIEW</p><h1 class="page-title">本机原型数据概览。</h1><section class="dashboard-grid"><article class="admin-metric"><span class="label">用户画像数</span><strong>${s.profile?1:0}</strong><span class="trend">当前浏览器</span></article><article class="admin-metric"><span class="label">今日状态记录</span><strong>${s.checkins.filter(x=>x.date===today()).length}</strong><span class="trend">本地数据</span></article><article class="admin-metric"><span class="label">训练记录</span><strong>${s.logs.length+s.strength.length}</strong><span class="trend">反馈 + 力量记录</span></article><article class="admin-metric"><span class="label">身体数据记录</span><strong>${s.metrics.length}</strong><span class="trend">本地数据</span></article></section><section class="admin-card"><h2>最近训练反馈</h2>${s.logs.length?`<div class="table-wrap"><table><thead><tr><th>日期</th><th>训练</th><th>完成</th><th>感觉</th><th>推荐准确度</th></tr></thead><tbody>${newest(s.logs).slice(0,5).map(l=>`<tr><td>${l.date}</td><td>${esc(l.workoutTitle)}</td><td>${l.completion}</td><td>${l.afterFeeling}</td><td>${l.recommendationAccuracy}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">暂时没有训练反馈。</p>'}</section>`}
function adminDistribution(){const s=stats(),max=Math.max(1,...s.distribution.map(x=>x.count));return `<p class="eyebrow">LAST 7 DAYS</p><h1 class="page-title">最近 7 天推荐类型。</h1><section class="admin-card"><div class="load-bars">${s.distribution.map(x=>`<div class="load-row"><span>${x.type}</span><div class="bar"><i style="width:${x.count/max*100}%"></i></div><b>${x.count}</b></div>`).join('')}</div><p class="tiny">仅统计当前浏览器 localStorage 中的状态记录。</p></section>`}
function adminFeedback(){const s=stats();return `<p class="eyebrow">TRAINING FEEDBACK</p><h1 class="page-title">最近训练反馈。</h1><section class="admin-card"><h2>常规反馈</h2>${s.logs.length?`<div class="table-wrap"><table><thead><tr><th>日期</th><th>训练</th><th>完成</th><th>感觉</th><th>备注</th></tr></thead><tbody>${newest(s.logs).map(l=>`<tr><td>${l.date}</td><td>${esc(l.workoutTitle)}</td><td>${l.completion}</td><td>${l.afterFeeling}</td><td>${esc(l.note||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">暂无反馈。</p>'}</section><section class="admin-card"><h2>力量记录</h2>${s.strength.length?`<div class="table-wrap"><table><thead><tr><th>日期</th><th>类型</th><th>训练</th><th>动作数</th><th>时长</th></tr></thead><tbody>${newest(s.strength).map(l=>`<tr><td>${l.date}</td><td>${l.workoutType}</td><td>${esc(l.workoutTitle)}</td><td>${l.exercises.filter(x=>x.name).length}</td><td>${l.durationMinutes||'—'} 分钟</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">暂无力量记录。</p>'}</section>`}
function adminData(){const s=stats(),preview={userProfile:s.profile||null,dailyCheckins:s.checkins.length,workoutLogs:s.logs.length,strengthWorkoutLogs:s.strength.length,bodyMetricLogs:s.metrics.length,storageKeys:STORAGE_KEYS};return `<p class="eyebrow">LOCAL STRUCTURE</p><h1 class="page-title">当前原型数据预览。</h1><section class="admin-card"><p>仅显示结构及当前浏览器中保存的数量，不上传任何信息。</p><pre class="data-preview">${esc(JSON.stringify(preview,null,2))}</pre></section>`}
function render(){if(state.mode==='admin')return admin();const f={welcome,profile,checkin,result,workout,feedback,records,library,action:movement,videos:videoLibrary,privacy}[state.screen]||welcome;f()}
function toUser(){history.replaceState('',document.title,`${location.pathname}${location.search}`);state.mode='user';state.screen='welcome';render()}
function valid(fields,d){const blank=fields.find(f=>f[3]?!(d[f[0]]||[]).length:!d[f[0]]);if(blank){tip(`请先完成「${blank[1].replace('？','')}」`);return false}return true}
function saveProfile(form){captureProfile(form);if(!valid(profileFields,state.profile))return;const p={...state.profile,activityLevel:state.profile.trainingLevel,createdAt:read(STORAGE_KEYS.USER_PROFILE,{}).createdAt||now(),updatedAt:now()};save(STORAGE_KEYS.USER_PROFILE,p);state.profile=p;eventLog('profile.saved','0.2 training context saved');state.screen='checkin';tip('基础设置已保存在本机');render()}
function saveCheckin(){if(!valid(checkinFields,state.checkin))return;const p=read(STORAGE_KEYS.USER_PROFILE,{}),r=calculateRecommendation(state.checkin,p),x={date:today(),...state.checkin,score:r.score,dayType:r.dayType,phase:r.phase.phase,createdAt:now()},a=read(STORAGE_KEYS.DAILY_CHECKINS,[]).filter(i=>i.date!==x.date);a.unshift(x);save(STORAGE_KEYS.DAILY_CHECKINS,a);state.last={...r,workouts:chooseWorkouts(p,r),checkin:x};eventLog('recommendation.created',`${r.dayType} · ${r.phase.phase}`);state.screen='result';render()}
function saveFeedback(form){captureFeedback(form);if(['completion','afterFeeling','recommendationAccuracy'].some(k=>!state.feedback[k]))return tip('请先完成这 3 项反馈');const w=workouts.find(x=>x.id===state.workoutId),log={date:today(),workoutId:w.id,workoutTitle:w.title,workoutType:w.type,completion:state.feedback.completion,afterFeeling:state.feedback.afterFeeling,recommendationAccuracy:state.feedback.recommendationAccuracy,note:state.feedback.note||'',createdAt:now()},logs=read(STORAGE_KEYS.WORKOUT_LOGS,[]).filter(x=>!(x.date===log.date&&x.workoutId===log.workoutId));logs.unshift(log);save(STORAGE_KEYS.WORKOUT_LOGS,logs);if(form.elements.strengthDuration)state.strength.durationMinutes=form.elements.strengthDuration.value;const has=state.strength.exercises.some(x=>x.name.trim())||state.strength.durationMinutes;if(has){const l={date:today(),workoutTitle:w.title,workoutType:w.type,durationMinutes:state.strength.durationMinutes,exercises:state.strength.exercises.filter(x=>Object.values(x).some(v=>String(v).trim())),note:state.strength.note||'',createdAt:now()},a=read(STORAGE_KEYS.STRENGTH_LOGS,[]).filter(x=>!(x.date===l.date&&x.workoutTitle===l.workoutTitle));a.unshift(l);save(STORAGE_KEYS.STRENGTH_LOGS,a)}eventLog('workout.feedback_saved',`${w.id} · ${log.completion}`);state.screen='records';state.recordTab=has?'training':'state';tip('已保存。你正在建立自己的训练节奏。');render()}
function saveMetric(form){const e=form.elements,has=['weight','waist','hip','thigh','sleepHours'].some(k=>e[k].value);if(!has)return tip('至少填写一项身体数据再保存');const x={date:today(),weight:e.weight.value,waist:e.waist.value,hip:e.hip.value,thigh:e.thigh.value,sleepHours:e.sleepHours.value,note:e.note.value.trim(),createdAt:now()},a=read(STORAGE_KEYS.BODY_METRICS,[]).filter(i=>i.date!==x.date);a.unshift(x);save(STORAGE_KEYS.BODY_METRICS,a);eventLog('body_metric.saved','body metric log saved');tip('身体数据已保存在本机');render()}
app.addEventListener('input',e=>{const t=e.target;if(t.dataset.strength){const i=Number(t.dataset.index);state.strength.exercises[i][t.dataset.strength]=t.value}if(t.name==='note'&&t.closest('#feedback-form'))state.feedback.note=t.value});
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;
 if(a==='pick'){if(b.dataset.kind==='profile')captureProfile();if(b.dataset.kind==='feedback')captureFeedback();const d=b.dataset.kind==='profile'?state.profile:b.dataset.kind==='checkin'?state.checkin:state.feedback,k=b.dataset.field,v=b.dataset.value,f=[...profileFields,...checkinFields].find(x=>x[0]===k);if(f?.[3]){const old=d[k]||[];if(!old.includes(v)&&old.length>=3)return tip('训练目标最多选择 3 项');d[k]=old.includes(v)?old.filter(x=>x!==v):[...old,v]}else d[k]=v;return render()}
 if(a==='start'){state.screen=read(STORAGE_KEYS.USER_PROFILE,null)?'checkin':'profile';render()}
 if(a==='go'){state.screen=b.dataset.screen;render()}
 if(a==='home'){state.screen='welcome';render()}
 if(a==='back-library'){state.screen='library';render()}
 if(a==='result'){state.screen='result';render()}
 if(a==='workout'){state.screen='workout';render()}
 if(a==='nav'){state.screen=b.dataset.screen==='result'&&!latest()?'checkin':b.dataset.screen;render()}
 if(a==='open-workout'){state.workoutId=b.dataset.id;state.screen='workout';render()}
 if(a==='open-action'){state.actionId=b.dataset.id;state.screen='action';render()}
 if(a==='complete-workout'){state.feedback={};state.strength={durationMinutes:'',exercises:[{name:'',weight:'',reps:'',sets:'',rpe:''}],note:''};state.screen='feedback';render()}
 if(a==='add-exercise'){captureFeedback();state.strength.exercises.push({name:'',weight:'',reps:'',sets:'',rpe:''});render()}
 if(a==='remove-exercise'){captureFeedback();state.strength.exercises.splice(Number(b.dataset.index),1);render()}
 if(a==='library-tab'){state.libraryTab=b.dataset.tab;render()}
 if(a==='record-tab'){state.recordTab=b.dataset.tab;render()}
 if(a==='video-placeholder')tip('这是外部视频资源占位卡，团队补充确认链接后会在新窗口打开。')
 if(a==='clear-data'&&confirm('确定清除本机的女训资料、状态、训练和身体数据吗？此操作不可恢复。')){[...Object.values(STORAGE_KEYS),...Object.values(LEGACY)].forEach(k=>localStorage.removeItem(k));state.profile={};state.checkin={};state.feedback={};state.last=null;state.workoutId=null;state.screen='welcome';tip('本地数据已清除');render()}
 if(a==='admin-logout'){localStorage.removeItem(STORAGE_KEYS.ADMIN_AUTH);toUser()}
 if(a==='admin-tab'){state.adminTab=b.dataset.tab;render()}
});
app.addEventListener('submit',e=>{e.preventDefault();const f=e.target;if(f.id==='profile-form')saveProfile(f);if(f.id==='checkin-form')saveCheckin();if(f.id==='feedback-form')saveFeedback(f);if(f.id==='body-form')saveMetric(f);if(f.id==='admin-login'){if(f.elements.password.value===ADMIN_PASSWORD){save(STORAGE_KEYS.ADMIN_AUTH,true);render()}else{const err=document.querySelector('#admin-error');if(err)err.textContent='密码错误，请重试。'}}});
window.addEventListener('hashchange',()=>{state.mode=location.hash==='#/admin'?'admin':'user';render()});
window.nvxun={calculateRecommendation,estimateCyclePhase,chooseWorkouts,workouts,actions,STORAGE_KEYS};
render();
})();
